// @vitest-environment happy-dom
/* eslint-disable react/prop-types */
/**
 * SchedulePDF.test.jsx — S4 (D10): one clinician-facing PDF component covers
 * both the routine forecast (`rows`) and the optimizer's plan (`visits`).
 * Verifies both bodies render, the generated-date + staleness lines appear
 * once, and the disclaimer is present in both variants.
 */

import { test, expect, vi } from 'vitest';
import { render } from '@testing-library/react';

// Mock @react-pdf/renderer (can't run in happy-dom) — same pattern as
// AdultCap.test.jsx / ComplianceAuditTab.test.jsx.
vi.mock('@react-pdf/renderer', () => ({
  Document: ({ children }) => <div>{children}</div>,
  Page: ({ children }) => <div>{children}</div>,
  Text: ({ children }) => <span>{children}</span>,
  View: ({ children }) => <div>{children}</div>,
  StyleSheet: { create: (s) => s },
}));

import SchedulePDF from '../SchedulePDF';

const routineRows = [
  {
    l: '4 months',
    date: 'Apr 1, 2026',
    isCurr: true,
    isCatchup: false,
    isPast: false,
    items: [
      { vk: 'DTaP', chip: 'Dose 2 of 5', brand: 'Infanrix', date: 'Apr 1, 2026' },
    ],
  },
  {
    l: '6 months',
    date: 'Jun 1, 2026',
    isCurr: false,
    isCatchup: false,
    isPast: false,
    items: [
      { vk: 'DTaP', chip: 'Dose 3 of 5', brand: '', date: 'Jun 1, 2026' },
    ],
  },
];

test('routine variant renders the full-forecast title and rows', () => {
  const { getByText } = render(
    <SchedulePDF
      am={4}
      dob="2026-01-01"
      risks={[]}
      rows={routineRows}
      recs={[]}
      fcBrands={{}}
      generatedAt="January 5, 2027"
    />
  );
  expect(getByText('Full Immunization Forecast')).toBeTruthy();
  expect(getByText('Visit-by-visit forecast')).toBeTruthy();
  expect(getByText('Infanrix')).toBeTruthy();
  expect(getByText('(brand to select)')).toBeTruthy();
});

test('optimizer variant renders the schedule title, mode, and visit summary', () => {
  const visits = [
    {
      date: '2026-04-01',
      items: [
        { vk: 'DTaP', doseNum: 2, totalDoses: 5, brand: 'Infanrix' },
      ],
    },
  ];
  const { getByText } = render(
    <SchedulePDF
      patient={{ name: 'Test Patient', dob: '2026-01-01', am: 4, risks: [] }}
      mode="fewestInjections"
      visits={visits}
      recs={[]}
      fcBrands={{}}
      generatedAt="2027-01-05"
    />
  );
  expect(getByText('Optimal Vaccine Schedule')).toBeTruthy();
  expect(getByText('Fewest injections (combo brands prioritized)')).toBeTruthy();
  expect(getByText(/1 visits · 1 injections/)).toBeTruthy();
});

test('the generated-date and staleness lines (D10) appear once, and the disclaimer is present', () => {
  const { getByText, getAllByText } = render(
    <SchedulePDF am={4} dob={null} risks={[]} rows={routineRows} recs={[]} fcBrands={{}} generatedAt="January 5, 2027" />
  );
  expect(getAllByText('Generated January 5, 2027 · For clinician review')).toHaveLength(1);
  expect(getByText(/These dates assume every dose is given on time/)).toBeTruthy();
  expect(getByText(/DISCLAIMER: This schedule is generated by PediVax/)).toBeTruthy();
});
