// SchedulePDF.jsx — the one clinician-facing schedule PDF (D10). Merged from
// the former separate ForecastPDF.jsx (routine ACIP timeline) and this file's
// prior optimizer-only version: same document shape, same disclaimer/footer,
// two body layouts selected by which props are passed. `visits` present means
// the optimizer's combo-bundled plan; otherwise it's the routine forecast
// built from `rows`. No family-facing template — this is for the clinician.
/* eslint-disable react/prop-types */
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { fmtAm } from '../logic/ageFormat';
import { todayISO } from '../logic/utils';
import { compactDoseChipLabel } from '../logic/dosePlan';
import { ShotListPage } from './ShotListPDF';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#222' },
  h1:   { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  h2:   { fontSize: 12, fontWeight: 700, marginTop: 14, marginBottom: 6, color: '#1a3a6b' },
  generatedLine: { fontSize: 10, color: '#222', fontWeight: 700, marginBottom: 2 },
  staleLine: { fontSize: 8.5, color: '#666', fontStyle: 'italic', marginBottom: 8 },
  metaRow:   { flexDirection: 'row', marginBottom: 2 },
  metaLabel: { width: 100, color: '#666', fontWeight: 700 },
  metaValue: { flex: 1 },
  divider: { borderBottom: '1pt solid #cccccc', marginVertical: 8 },

  visitHeader: { flexDirection: 'row', padding: 4, marginTop: 6 },
  visitHeaderText: { color: '#ffffff', fontSize: 10, fontWeight: 700 },
  visitBox: { border: '1pt solid #d8e1eb', borderTop: 0, padding: 6, marginBottom: 4 },

  doseRow:   { flexDirection: 'row', paddingVertical: 1.5 },
  doseVk:    { width: 70, fontWeight: 700 },
  doseDose:  { width: 80, color: '#555' },
  doseNum:   { width: 50, color: '#555' },
  doseBrand: { flex: 1, color: '#555' },
  doseDate:  { fontSize: 7.5, color: '#888', fontStyle: 'italic' },

  comboRow: {
    flexDirection: 'row', backgroundColor: '#fff8d8',
    paddingVertical: 3, paddingHorizontal: 4, marginVertical: 1,
  },
  comboName: { width: 90, fontWeight: 700, color: '#856404' },
  comboCovers: { flex: 1, color: '#666', fontSize: 9 },

  providerBlock: {
    marginTop: 16, padding: 8, border: '1pt solid #d8e1eb',
    backgroundColor: '#fafbfc',
  },
  providerLabel: { fontSize: 9, color: '#666', marginBottom: 8 },
  providerLine:  { borderBottom: '0.5pt solid #999', height: 16, marginBottom: 4 },

  disclaimer: {
    marginTop: 12, padding: 6, fontSize: 8, color: '#666',
    fontStyle: 'italic', backgroundColor: '#fff3cd', border: '1pt solid #f0c040',
  },
  footer: {
    position: 'absolute', bottom: 24, left: 40, right: 40,
    fontSize: 7, color: '#999', textAlign: 'center',
  },
});

const MODE_LABELS = {
  fewestVisits: 'Fewest visits',
  earliestCompletion: 'Earliest completion',
  fewestInjections: 'Fewest injections (combo brands prioritized)',
};

function fmtRiskList(risks) {
  if (!risks || risks.length === 0) return 'None entered';
  return risks.join(', ');
}

function ageAtDateStr(dob, date) {
  if (!dob) return '';
  const ms = new Date(date) - new Date(dob);
  const days = ms / (1000 * 60 * 60 * 24);
  const months = days / 30.4375;
  if (months < 24) return `${Math.round(months)} months`;
  return `${(months / 12).toFixed(1)} years`;
}

function GeneratedHeader({ today }) {
  return (
    <>
      <Text style={styles.generatedLine}>Generated {today} · For clinician review</Text>
      <Text style={styles.staleLine}>
        These dates assume every dose is given on time. If a dose is missed or given early, ask for a new copy.
      </Text>
    </>
  );
}

function Disclaimer({ today }) {
  return (
    <>
      <View style={styles.providerBlock}>
        <Text style={styles.providerLabel}>Provider / Clinic:</Text>
        <View style={styles.providerLine} />
        <Text style={styles.providerLabel}>Clinician signature / date:</Text>
        <View style={styles.providerLine} />
      </View>

      <View style={styles.disclaimer}>
        <Text>
          {'DISCLAIMER: This schedule is generated by PediVax for clinician review and is NOT medical advice. All dose timing, brand selection, and contraindication review must be verified against current CDC/ACIP guidance and the manufacturer\'s prescribing information before any vaccine is administered. Schedule may change based on availability, intercurrent illness, contraindications, or new clinical findings. PediVax authors and operators assume no responsibility for clinical decisions made on the basis of this output.'}
        </Text>
      </View>

      <Text
        style={styles.footer}
        fixed
        render={({ pageNumber, totalPages }) =>
          `PediVax · Generated ${today} · Page ${pageNumber} of ${totalPages}`
        }
      />
    </>
  );
}

function RoutineBody({ am, dob, risks, rows }) {
  const dobFmt = dob
    ? new Date(dob + 'T12:00:00').toLocaleDateString('en-US', {
        month: 'short', day: 'numeric', year: 'numeric',
      })
    : null;

  const visibleRows = rows.filter(r => r.isCurr || r.items.length > 0);

  return (
    <>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Patient name:</Text>
        <Text style={styles.metaValue}>_____________________________</Text>
      </View>
      {dobFmt && (
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Date of birth:</Text>
          <Text style={styles.metaValue}>{dobFmt}</Text>
        </View>
      )}
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Current age:</Text>
        <Text style={styles.metaValue}>{fmtAm(am)}</Text>
      </View>
      {risks && risks.length > 0 && (
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Risk factors:</Text>
          <Text style={styles.metaValue}>{fmtRiskList(risks)}</Text>
        </View>
      )}

      <Text style={styles.h2}>Visit-by-visit forecast</Text>

      {visibleRows.map((row, i) => {
        const bgColor = row.isCurr ? '#2e7d32'
          : row.isCatchup ? '#b45309'
          : row.isPast ? '#888'
          : '#1a3a6b';

        const visitLabel = row.isCurr
          ? `▶ ${row.l} — CURRENT VISIT`
          : row.isCatchup ? `${row.l} (catch-up)`
          : row.l;

        return (
          <View key={i} wrap={false}>
            <View style={[styles.visitHeader, { backgroundColor: bgColor }]}>
              <Text style={[styles.visitHeaderText, { flex: 1 }]}>{visitLabel}</Text>
              {row.date
                ? <Text style={styles.visitHeaderText}>{row.date}</Text>
                : null}
            </View>
            <View style={styles.visitBox}>
              {row.items.length > 0
                ? row.items.map((item, j) => {
                    const brandShort = item.brand
                      ? item.brand.split('(')[0].trim()
                      : '(brand to select)';
                    return (
                      <View key={j} style={styles.doseRow}>
                        <Text style={styles.doseVk}>{item.vk}</Text>
                        <Text style={styles.doseDose}>{item.chip}</Text>
                        <Text style={styles.doseBrand}>{brandShort}</Text>
                        {item.date
                          ? <Text style={styles.doseDate}>{item.date}</Text>
                          : null}
                      </View>
                    );
                  })
                : <Text style={{ fontSize: 9, color: '#888' }}>No vaccines due</Text>}
            </View>
          </View>
        );
      })}
    </>
  );
}

function VisitItems({ items, chipCtx }) {
  return (
    <>
      {items.map((it, i) => {
        if (it._combo) {
          return (
            <View key={i} style={styles.comboRow} wrap={false}>
              <Text style={styles.comboName}>{it.comboName}</Text>
              <Text style={styles.comboCovers}>
                covers {it.coveredAntigens.join(' + ')} (
                {it.coveredDoses.map(d => `${d.vk} ${compactDoseChipLabel(d.vk, d.doseNum, d.totalDoses, chipCtx)}`).join(', ')})
              </Text>
            </View>
          );
        }
        const brandShort = it.brand ? it.brand.split('(')[0].trim() : '(brand to select)';
        return (
          <View key={i} style={styles.doseRow} wrap={false}>
            <Text style={styles.doseVk}>{it.vk}</Text>
            <Text style={styles.doseNum}>{compactDoseChipLabel(it.vk, it.doseNum, it.totalDoses, chipCtx)}</Text>
            <Text style={styles.doseBrand}>{brandShort}</Text>
          </View>
        );
      })}
    </>
  );
}

function OptimizerBody({ patient, mode, visits }) {
  // N4: what the dose chips need before printing a total — some meningococcal
  // schedules never finish. See compactDoseChipLabel in dosePlan.js.
  const chipCtx = { risks: patient.risks || [], hist: patient.hist || {}, dob: patient.dob || null };
  const totalDoses = visits.reduce((s, v) => s + v.items.reduce((s2, it) => s2 + (it._combo ? it.coveredDoses.length : 1), 0), 0);
  const totalInjections = visits.reduce((s, v) => s + v.items.length, 0);
  const lastVisitDate = visits.at(-1)?.date;

  return (
    <>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Patient name:</Text>
        <Text style={styles.metaValue}>{patient.name || '_____________________________'}</Text>
      </View>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Date of birth:</Text>
        <Text style={styles.metaValue}>{patient.dob || '_____________'}</Text>
      </View>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Current age:</Text>
        <Text style={styles.metaValue}>{patient.am} months</Text>
      </View>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Risk conditions:</Text>
        <Text style={styles.metaValue}>{fmtRiskList(patient.risks)}</Text>
      </View>
      <View style={styles.metaRow}>
        <Text style={styles.metaLabel}>Schedule mode:</Text>
        <Text style={styles.metaValue}>{MODE_LABELS[mode] || mode}</Text>
      </View>

      <Text style={styles.h2}>Summary</Text>
      <Text>{visits.length} visits · {totalInjections} injections ({totalDoses} antigen doses) · series complete by {lastVisitDate || 'N/A'}</Text>

      <Text style={styles.h2}>Visit-by-visit plan</Text>
      {visits.map((v, i) => (
        <View key={i} wrap={false}>
          <View style={[styles.visitHeader, { backgroundColor: '#1a3a6b' }]}>
            <Text style={[styles.visitHeaderText, { flex: 1 }]}>Visit {i + 1} — {v.date}</Text>
            <Text style={styles.visitHeaderText}>
              Age: {ageAtDateStr(patient.dob, v.date)} · {v.items.length} injection{v.items.length !== 1 ? 's' : ''}
            </Text>
          </View>
          <View style={styles.visitBox}>
            <VisitItems items={v.items} chipCtx={chipCtx} />
          </View>
        </View>
      ))}
    </>
  );
}

export default function SchedulePDF(props) {
  const { am, dob, risks, rows, patient, mode, visits, recs, fcBrands, generatedAt } = props;
  const isOptimizer = Array.isArray(visits);

  const today = generatedAt || (isOptimizer
    ? todayISO()
    : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));

  const title = isOptimizer ? 'Optimal Vaccine Schedule' : 'Full Immunization Forecast';
  const docTitle = isOptimizer
    ? `PediVax Schedule — ${patient?.name || 'Patient'} (${today})`
    : `PediVax Full Forecast — ${today}`;
  const shotListAm = isOptimizer ? patient.am : am;
  const shotListDob = isOptimizer ? patient.dob : dob;

  return (
    <Document title={docTitle} author="PediVax">
      {/* Today's admin/shot-list page first, then the visit-by-visit plan —
          one download covers both what to give today and what's coming. */}
      {recs && recs.length > 0 && <ShotListPage am={shotListAm} dob={shotListDob} recs={recs} fcBrands={fcBrands} />}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>{title}</Text>
        <GeneratedHeader today={today} />

        <View style={styles.divider} />

        {isOptimizer
          ? <OptimizerBody patient={patient} mode={mode} visits={visits} />
          : <RoutineBody am={am} dob={dob} risks={risks} rows={rows} />}

        <Disclaimer today={today} />
      </Page>
    </Document>
  );
}
